// Import Better Auth schema generated by CLI
export * from "./auth.schema";

// Re-export all schemas from organized modules
export * from "./schemas/workout.schema";
export * from "./schemas/user.schema";
export * from "./schemas/ai.schema";
export * from "./schemas/billing.schema";
export * from "./schemas/relations";